// All action codes to begin with 2
let NO_ACTION = 20;
let MOVE_SPACES = 21;
let PAY_MONEY = 22;
let RECIEVE_MONEY = 23;
let GO_TO_JAIL = 24;
let GET_OUT_OF_JAIL = 25
let PASS_GO = 26;
let PICK_CHANCE = 27;
let PICK_COMMUNITY_CHEST = 28;
let MORTGAGE = 29;
let AUCTION = 210;
let BUY_PROPERTY = 211;
let BUILD_HOUSE = 212;
let DESTROY_HOUSE = 213;
let UNMORTGAGE = 214;