let CANNOT_MOVE = 1;
let INSUFFICIENT_FUNDS = 2;
let CANNOT_BUILD_HOUSES = 3;
let CANNOT_BUY_PROPERTY = 4;
let CANNOT_MORTGAGE = 5;
let CANNOT_UNMORTGAGE = 6;
let CANNOT_DESTROY_HOUSES = 7;
let CANNOT_PAY_RENT_TO_YOURSELF = 8;