// All error codes to begin with 1
let INVALID_RESPONSE = 10;
let CANNOT_MOVE = 11;
let INSUFFICIENT_FUNDS = 12;
let CANNOT_BUILD_HOUSES = 13;
let CANNOT_BUY_PROPERTY = 14;
let CANNOT_MORTGAGE = 15;
let CANNOT_UNMORTGAGE = 16;
let CANNOT_DESTROY_HOUSES = 17;